app/base/urls.py
from django.urls import path
from . import views


app_name = 'base'

urlpatterns = [
    # path('', views.home, name='home'),
    path('', views.HomeView.as_view(), name='home'),
    path('checker', views.CheckerView.as_view(), name='checker'),
]

app/dum/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
]

app/base/models.py
from django.db import models

# Create your models here.

app/base/forms.py
from django import forms


class UploadFileForm(forms.Form):
    table = forms.FileField()

app/base/views.py
# from django.shortcuts import render
from django.views import generic
from django.views.generic.base import TemplateResponseMixin
from django.views.generic.edit import FormMixin

import checker

from .forms import UploadFileForm


class HomeView(generic.RedirectView):
    url = '/checker'


class CheckerView(TemplateResponseMixin, FormMixin, generic.View):
    template_name = 'checker.html'
    form_class = UploadFileForm

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            table = form.cleaned_data['table']
            checks = checker.check(table.name, table.file)
            context = self.get_context_data(form=form, checks=checks)
            return self.render_to_response(context)
        return self.form_invalid(form)

app/base/templates/base.html
<!doctype html>

{% load static %}

<html lang="bg-BG">

<head>
  <meta charset="utf-8">
  <title>{% block title %}Начало{% endblock title %}</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">

  <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icons/apple-icon-57x57.png' %}">
  <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icons/apple-icon-60x60.png' %}">
  <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icons/apple-icon-72x72.png' %}">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icons/apple-icon-76x76.png' %}">
  <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icons/apple-icon-114x114.png' %}">
  <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icons/apple-icon-120x120.png' %}">
  <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icons/apple-icon-144x144.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icons/apple-icon-152x152.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-icon-180x180.png' %}">
  <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'icons/android-icon-192x192.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icons/favicon-96x96.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'icons/manifest.json' %}">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="{% static 'icons/ms-icon-144x144.png' %}">
  <meta name="theme-color" content="#ffffff">  

  {% block css %}
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  {% endblock css %}

  <link rel="manifest" href="site.webmanifest">
  <meta name="theme-color" content="#fafafa">
</head>

<body class="bg-dark text-light">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'base:home' %}">dum</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'base:checker' %}">проверка</a>
          </li>
        </ul>
      </div> <!-- .collapse -->
    </div> <!-- .container -->
  </nav>
  
  {% block body %}{% endblock %}

  {% block js %}{% endblock %}

</body>

</html>

app/base/templates/checker.html
{% extends "base.html" %}

{% block title %}Проверка{% endblock title %}

{% block body %}

<div class="container">
  <div class="row">
    <div class="col">
      <p class="mt-2">
        Този уебсайт <b>не съхранява</b> проверяваните файлове.

        Проектът е
        <a class="link-info" href="https://www.gnu.org/philosophy/free-sw.bg.html">свободен</a>,
        кодът е поместен <a class="link-info" href="https://github.com/ydm/dum">тук</a>.
      </p>
    </div> <!-- .col -->
  </div> <!-- .row -->

  {% if form.is_valid %}
    <div class="row">
      <div class="col">
        <p>
          Файлът <code>{{ form.cleaned_data.table.name }}</code> бе качен и проверен.
        </p>

        {% if checks %}
          {% for check in checks %}
            <div class="alert alert-warning" role="alert">
              {{ check|capfirst }}
            </div>
          {% endfor checks %}
        {% else %}
          <div class="alert alert-success" role="alert">Не са открити грешки!</div>
        {% endif %}
      </div> <!-- .col -->
    </div> <!-- .row -->
  {% else %}
    <p>
      Качете таблица (UTF-8 кодиран CSV, ODF или XLSX) с попълнени
      референдумни данни:
    </p>
  {% endif %}

  {% if checks %}
    <div class="row">
      <div class="col">
        {% for check in checks %}
          
        {% endfor %}
      </div> <!-- .col -->
    </div> <!-- .row -->
  {% endif %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="row align-items-center">
      <div class="col-auto">
        {{ form.as_div }}
      </div> <!-- .col-auto -->
      <div class="col-auto">
        <button class="btn btn-info" type="submit">Прикачи</button>
      </div> <!-- .col-auto -->
    </div> <!-- .row -->
  </form>

</div> <!-- .container -->

{% endblock body %}